### ISSUE TITLE
Teacher Backend: Validator Script Update Notification

### ISSUE THREAD

**Issue by adonnen** [troeger/opensubmit#121]
If the script is updated while there are existing submission, then the script should be re-executed for the existing submissions or at least a notification email should be sent to all students who already have submitted their solutions

**Comment by troeger** [comment]
While this is already manually possible ("Mark as new incoming submission"), it makes sense to automate it, since there is no case where you don't want that to happen.

**Comment by troeger** [comment]
This demands custom signal sending from the assignment admin clean() method, because there is no other way to figure out that the test scripts (and nothing else) were modified. 

This is a larger patch and needs according test cases. Therefore, we delay it to a later release. Please use the hint above until then.
