### ISSUE TITLE
No etc/opensubmit/apache24.conf  file deployed

### ISSUE THREAD

**Issue by optimum-web** [troeger/opensubmit#164]
No etc/opensubmit/apache24.conf  file deployed
where can I find it ? 

Best regards

**Comment by optimum-web** [comment]
sorry, I should had read documentation. But such deployment is not user friendly, should be splitted probably into two phases. One is setup ini files and second generating configuration basing on it

**Comment by troeger** [comment]
I re-open that issue, because I totally agree that the current setup procedure is a mess.

The idea would be to have a new "opensubmit-web initialize" command. We may want to print a hint for the command after the first PyPI installation, but not after updates of the software.

The command should:

  * ... ask for the mandatory settings (HOST, HOST_DIR, MEDIA_ROOT) interactively,
  * ... generate a default /etc/opensubmit/settings.ini based on that.
  * ... generate a default /etc/opensubmit/apache24.conf based on that.
  * ... try to integrate the Apache config file automatically (conf.d ?!?).
  * ... restart the web server on success.
  * ... call "opensubmit-web configure" to generate a valid SQLite database, which is the default setup.
  * ... call "opensubmit-web createsuperuser" to generate the admin account interactively..
  * ... call "opensubmit-web createdemo" to generate some default course and assignment for playing around.
  * ... print a hint for `settings.ini` and `opensubmit-web configure`.

All in all, this would generate a working OpenSubmit installation with SQLite and StackOverflow OpenID login in one step. 

We may want to support the above parameters as command-line arguments, so that unattended installation (with default admin credentials?) is supported.

**Comment by optimum-web** [comment]
Thanks for reopening it. 
I would use python-fabric or Ansible for that purposes.  This would put installation process apart from the application itself. As far as I know with Ansible playbook, application can be installed/deployed on many different platforms,  you don't care about where to put apache.conf file or nginx.conf. Another one is Dockerfile, but that's another story. 

Best regards

**Comment by troeger** [comment]
Ok, this issue remained open so far as a constant reminder for me.

With the last commit in the Master branch, we now have support for Docker-based installation of OpenSubmit. A detailled documentation is provided with a [manual](http://open-submit.org/formats/html/admin_use.html) update very soon. I also plan to push this whole thing into Docker Hub, so that installation becomes even more trivial.

Installation steps for OpenSubmit are therefore, from now on, explicitely documented here [here](http://open-submit.org/formats/html/admin_use.html), and implicitly documented [here](https://github.com/troeger/opensubmit/blob/master/web/Dockerfile) resp. [here](https://github.com/troeger/opensubmit/blob/master/executor/Dockerfile) .
