### ISSUE TITLE
Permission reset

### ISSUE THREAD

**Issue by thehappyhippo** [troeger/opensubmit#70]
Is there some code that resets the permissions? Because I change user permissions and after some time the permissions are reset to their previous values. The values were persisted to the db, so it has to be code maybe db code that changes the values. I known I have to upgrade but I think it is in the current code also.

**Comment by troeger** [comment]
Yes, this is here:

https://github.com/troeger/opensubmit/blob/master/web/opensubmit/signalhandlers.py

Please read the comments carefully. You should also consider that this was changed very recently, so your installed version surely does not look like this.

**Comment by thehappyhippo** [comment]
We have the problem that we need multiple course owner per course. If I add a user as tutor for a course and assign the user the course owner rights then they get the right permission set. But https://github.com/troeger/opensubmit/blob/master/web/opensubmit/signalhandlers.py#L9 removes the course owner role, because of the order of checking. I now added the [add,change,delete] assignment rights to test if they persist. Maybe we allow multiple course owners.

**Comment by troeger** [comment]
You are right, the problem is here:

https://github.com/troeger/opensubmit/blob/master/web/opensubmit/signalhandlers.py#L50

This deletes unintentionally all manual assignments of people to the course owner group, which is non-sense. You 'hack' solves the problem, but the course owner group assignment should work.
