### ISSUE TITLE
Executor starts way to many concurrent instances

### ISSUE THREAD

**Issue by Feinbube** [troeger/opensubmit#76]
![image](https://cloud.githubusercontent.com/assets/5708998/10934062/898a6fb2-82dd-11e5-87c1-9d4a85262480.png)

**Comment by troeger** [comment]
What is the setting of the "serialize" parameter in the executor configuration on this machine?

If it set to yes, we need you to debug the problem on the host, since this should not happen.  There must be a reason why all the different safeguards in the code do not remove the existing processes.

If it set to no, then this is the expected behavior.

**Comment by Feinbube** [comment]
# Do you allow multiple executor instances at the same time ?
# The answer is always "NO" when the validation is gathering performance numbers
# Please note that this also delays compile jobs
serialize=True
pidfile=/tmp/executor.pid

This problem still occurs. Seems we need to debug this, then.

**Comment by troeger** [comment]
Ok, in this case we need the binaries that reject to be killed by the executor timeout mechanism. Could you please provide an according test case?

**Comment by Feinbube** [comment]
Sent by mail.

**Comment by Feinbube** [comment]
This has been fixed, right?

**Comment by troeger** [comment]
See the discussion in #69. I really don't know.

**Comment by Feinbube** [comment]
I think it's closed. It the problem occurs again, we just re-open this ;)

**Comment by troeger** [comment]
Works for me.
